name: Actions Workflow

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        id: greet
        run: echo "Nice Start Vishal"
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"
  run-windows-commands:
    runs-on: windows-latest
    steps:
      - name: Directory Powershell
        run: Get-Location
      - name: Directory Bash
        run: pwd
        shell: bash
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Simple Js Actions
        uses: ./.github/actions/my-action